
spring:
  cloud:
    nacos:
      discovery:
#        register-enabled: true
        server-addr: 172.16.248.188:8848 # nancos地址
  application:
    name: com.example.service-provider
server:
  port: 8070