server:
  port: 8080

spring:
    redis:
        host: 172.16.248.188
        jedis:
            pool:
                max-active: 100
                max-idle: 100
                max-wait: -1
                min-idle: 1
        password: ''
        port: 6379
